previewsEnabled: true
services:
  - type: web
    name: Sophies Demo API
    env: node
    plan: free
    region: singapore
    repo: https://github.com/psse-cpu/sophies-demo-2022.git
    buildCommand: pnpm be deploy
    startCommand: pnpm be start:prod
    pullRequestPreviewsEnabled: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_OAUTH_REDIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - fromGroup: shared-secrets
    autoDeploy: false # optional

  - type: web
    name: Sophies Demo API Staging
    env: node
    plan: free
    region: singapore
    repo: https://github.com/psse-cpu/sophies-demo-2022.git
    buildCommand: pnpm be deploy
    startCommand: pnpm be start:prod
    pullRequestPreviewsEnabled: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_OAUTH_REDIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - fromGroup: shared-secrets
    autoDeploy: false # optional

  # A static site
  - type: web
    name: Sophies Demo
    env: static
    buildCommand: pnpm fe deploy
    staticPublishPath: ./frontend/dist/spa
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: false

  - type: web
    name: Sophies Demo Staging
    env: static
    buildCommand: pnpm fe deploy
    staticPublishPath: ./frontend/dist/spa
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: false

envVarGroups:
  - name: shared-secrets
    envVars:
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1w
